export type PlanetKey =
  | "mercury"
  | "venus"
  | "earth"
  | "mars"
  | "jupiter"
  | "saturn"
  | "uranus"
  | "neptune"
  | "pluto";

export type Mission = {
  slug: string;
  code: string;
  title: string;
  planet: PlanetKey;
  planetKo: string;
  sector: string;
  orbit: number;
  level: string;
  difficulty: number;
  time: string;
  threat: string;
  reward: string;
  desc: string;
  summary: string;
  analogy: string;
  concepts: string[];
  steps: string[];
  codeSnippet: string;
  experiment: {
    dropout: number;
    epochs: number;
    complexity: number;
  };
};

export const planets = [
  {
    key: "mercury" as const,
    name: "Mercury",
    ko: "수성",
    sector: "Data Core",
    desc: "데이터셋, Feature, Label, Train/Test Split",
    level: "기초",
    href: "/mission/dataset-core",
    orbit: 1,
    image: "/planets/mercury.png",
  },
  {
    key: "venus" as const,
    name: "Venus",
    ko: "금성",
    sector: "Preprocessing",
    desc: "스케일링, 인코딩, 결측치, 특성공학",
    level: "기초",
    href: "/academy",
    orbit: 2,
    image: "/planets/venus.png",
  },
  {
    key: "earth" as const,
    name: "Earth",
    ko: "지구",
    sector: "Supervised ML",
    desc: "회귀, 분류, 손실함수, 평가 지표",
    level: "입문",
    href: "/galaxy",
    orbit: 3,
    image: "/planets/earth.png",
  },
  {
    key: "mars" as const,
    name: "Mars",
    ko: "화성",
    sector: "Classic ML",
    desc: "KNN, RandomForest, SVM, K-Means, PCA",
    level: "중급",
    href: "/mission/randomforest",
    orbit: 4,
    image: "/planets/mars.png",
  },
  {
    key: "jupiter" as const,
    name: "Jupiter",
    ko: "목성",
    sector: "Deep Learning",
    desc: "Perceptron, MLP, Backpropagation",
    level: "중상",
    href: "/mission/overfitting",
    orbit: 5,
    image: "/planets/jupiter.png",
  },
  {
    key: "saturn" as const,
    name: "Saturn",
    ko: "토성",
    sector: "CNN Vision",
    desc: "Convolution, Pooling, Padding, Stride",
    level: "중상",
    href: "/mission/cnn",
    orbit: 6,
    image: "/planets/saturn.png",
  },
  {
    key: "uranus" as const,
    name: "Uranus",
    ko: "천왕성",
    sector: "Generalization",
    desc: "Dropout, EarlyStopping, ResNet, Optimization",
    level: "심화",
    href: "/mission/dropout",
    orbit: 7,
    image: "/planets/uranus.png",
  },
  {
    key: "neptune" as const,
    name: "Neptune",
    ko: "해왕성",
    sector: "Transformer",
    desc: "Attention, Transformer, LLM 기초",
    level: "고급",
    href: "/mission/transformer",
    orbit: 8,
    image: "/planets/neptune.png",
  },
  {
    key: "pluto" as const,
    name: "Pluto",
    ko: "명왕성",
    sector: "Frontier AI",
    desc: "YOLO, Transfer Learning, Generative AI",
    level: "최전선",
    href: "/mission/yolo",
    orbit: 9,
    image: "/planets/pluto.png",
  },
];

export const missions: Mission[] = [
  {
    slug: "dataset-core",
    code: "M-00",
    title: "Dataset Core",
    planet: "mercury",
    planetKo: "수성",
    sector: "Data Core",
    orbit: 1,
    level: "기초",
    difficulty: 2,
    time: "8분",
    threat: "Data Leakage",
    reward: "Data Sense Badge",
    desc: "AI 학습의 원료인 데이터 구조를 이해합니다.",
    summary: "모델은 데이터에서 규칙을 배우므로 데이터 품질과 분리 방식이 성능의 출발점입니다.",
    analogy: "요리사가 아무리 뛰어나도 재료가 상하면 좋은 요리가 나오지 않는 것과 같습니다.",
    concepts: ["Dataset", "Feature", "Label", "Train/Test Split", "Data Leakage"],
    steps: ["입력 X와 정답 y를 구분합니다.", "훈련/검증/테스트 데이터를 나눕니다.", "데이터 누수가 왜 위험한지 확인합니다.", "좋은 데이터셋의 조건을 정리합니다."],
    codeSnippet: `from sklearn.model_selection import train_test_split\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42\n)`,
    experiment: { dropout: 0.05, epochs: 10, complexity: 2 },
  },
  {
    slug: "randomforest",
    code: "M-01",
    title: "RandomForest Citadel",
    planet: "mars",
    planetKo: "화성",
    sector: "Classic ML",
    orbit: 4,
    level: "중급",
    difficulty: 3,
    time: "12분",
    threat: "Tabular Dominion",
    reward: "Forest Ensemble Core",
    desc: "여러 결정트리가 투표하는 강력한 표 데이터 모델입니다.",
    summary: "RandomForest는 여러 결정트리를 학습시켜 투표 또는 평균으로 안정적인 예측을 만듭니다.",
    analogy: "한 명의 전문가가 아니라 여러 전문가에게 물어보고 다수결로 결정하는 방식입니다.",
    concepts: ["Decision Tree", "Ensemble", "Bagging", "Feature Importance", "Tabular Data"],
    steps: ["결정트리가 데이터를 나누는 방식을 이해합니다.", "여러 트리가 각자 다른 관점으로 학습합니다.", "앙상블이 과적합을 줄이는 이유를 봅니다.", "표 데이터에서 강한 이유를 정리합니다."],
    codeSnippet: `from sklearn.ensemble import RandomForestClassifier\n\nmodel = RandomForestClassifier(n_estimators=300, max_depth=8, random_state=42)\nmodel.fit(X_train, y_train)\nprint(model.score(X_test, y_test))`,
    experiment: { dropout: 0, epochs: 30, complexity: 4 },
  },
  {
    slug: "cnn",
    code: "M-02",
    title: "CNN Saturn Station",
    planet: "saturn",
    planetKo: "토성",
    sector: "CNN Vision",
    orbit: 6,
    level: "중상",
    difficulty: 4,
    time: "18분",
    threat: "Feature Chaos",
    reward: "Feature Extractor Badge",
    desc: "이미지를 필터로 스캔해 특징을 추출합니다.",
    summary: "CNN은 이미지의 작은 영역을 필터로 훑으며 선, 모서리, 질감 같은 특징을 추출합니다.",
    analogy: "사람이 얼굴을 볼 때 눈, 코, 윤곽을 부분적으로 보고 합쳐서 인식하는 것과 비슷합니다.",
    concepts: ["Convolution", "Filter", "Kernel", "Feature Map", "Pooling", "Stride", "Padding"],
    steps: ["이미지가 숫자 배열이라는 점을 봅니다.", "필터가 이미지를 훑는 과정을 이해합니다.", "Pooling이 정보를 압축하는 이유를 확인합니다.", "Dense 모델보다 이미지에 강한 이유를 정리합니다."],
    codeSnippet: `from tensorflow.keras import layers, models\n\nmodel = models.Sequential([\n    layers.Conv2D(32, (3, 3), activation="relu", input_shape=(32, 32, 3)),\n    layers.MaxPooling2D((2, 2)),\n    layers.Conv2D(64, (3, 3), activation="relu"),\n    layers.Flatten(),\n    layers.Dense(10, activation="softmax")\n])`,
    experiment: { dropout: 0.2, epochs: 20, complexity: 6 },
  },
  {
    slug: "resnet",
    code: "M-03",
    title: "ResNet Uranus Gate",
    planet: "uranus",
    planetKo: "천왕성",
    sector: "Generalization",
    orbit: 7,
    level: "심화",
    difficulty: 5,
    time: "20분",
    threat: "Vanishing Gradient",
    reward: "Skip Connection Core",
    desc: "깊은 신경망에 shortcut을 만들어 정보 흐름을 보존합니다.",
    summary: "ResNet은 깊은 신경망에서 정보와 기울기가 사라지지 않도록 shortcut connection을 추가한 구조입니다.",
    analogy: "복잡한 미로에 지름길을 만들어 신호가 멀리까지 안정적으로 이동하게 하는 것과 같습니다.",
    concepts: ["Residual Learning", "Skip Connection", "Gradient Flow", "Deep Network"],
    steps: ["깊은 신경망에서 학습이 어려워지는 이유를 봅니다.", "기울기 소실 문제를 이해합니다.", "Skip Connection의 역할을 확인합니다.", "ResNet이 깊은 모델을 가능하게 한 이유를 정리합니다."],
    codeSnippet: `def residual_block(x):\n    shortcut = x\n    x = Conv2D(64, 3, padding="same", activation="relu")(x)\n    x = Conv2D(64, 3, padding="same")(x)\n    x = Add()([x, shortcut])\n    return Activation("relu")(x)`,
    experiment: { dropout: 0.2, epochs: 35, complexity: 8 },
  },
  {
    slug: "overfitting",
    code: "M-04",
    title: "Overfitting Jupiter Storm",
    planet: "jupiter",
    planetKo: "목성",
    sector: "Deep Learning",
    orbit: 5,
    level: "중상",
    difficulty: 5,
    time: "15분",
    threat: "Memorization Collapse",
    reward: "Generalization Shield",
    desc: "훈련 데이터만 외워버리는 위험을 이해합니다.",
    summary: "과적합은 모델이 훈련 데이터에는 강하지만 처음 보는 데이터에는 약해지는 현상입니다.",
    analogy: "문제집 답만 외워서 비슷한 문제는 맞히지만 새 문제가 나오면 틀리는 학생과 같습니다.",
    concepts: ["Train Accuracy", "Validation Accuracy", "Generalization", "Regularization"],
    steps: ["훈련 정확도와 검증 정확도의 차이를 봅니다.", "모델이 데이터를 외우는 상황을 이해합니다.", "복잡한 모델이 항상 좋은 것은 아님을 확인합니다.", "일반화 방어 전략을 정리합니다."],
    codeSnippet: `history = model.fit(\n    X_train, y_train,\n    validation_data=(X_test, y_test),\n    epochs=100\n)`,
    experiment: { dropout: 0, epochs: 80, complexity: 9 },
  },
  {
    slug: "dropout",
    code: "M-05",
    title: "Dropout Uranus Shield",
    planet: "uranus",
    planetKo: "천왕성",
    sector: "Generalization",
    orbit: 7,
    level: "심화",
    difficulty: 4,
    time: "14분",
    threat: "Neuron Dependency",
    reward: "Anti-Overfit Armor",
    desc: "일부 뉴런을 꺼서 특정 경로 의존을 줄입니다.",
    summary: "Dropout은 학습 중 일부 뉴런을 랜덤하게 꺼서 특정 뉴런에 과하게 의존하는 것을 막습니다.",
    analogy: "항상 같은 팀원에게만 의존하지 않도록 랜덤으로 쉬게 해서 모두가 골고루 실력을 키우게 하는 훈련입니다.",
    concepts: ["Dropout Rate", "Regularization", "Co-adaptation", "Generalization"],
    steps: ["뉴런이 특정 경로에만 의존하는 상황을 봅니다.", "Dropout으로 일부 뉴런을 비활성화합니다.", "0.5와 0.9의 차이를 비교합니다.", "너무 큰 Dropout의 위험을 정리합니다."],
    codeSnippet: `model = models.Sequential([\n    layers.Dense(256, activation="relu"),\n    layers.Dropout(0.5),\n    layers.Dense(128, activation="relu"),\n    layers.Dropout(0.3),\n    layers.Dense(10, activation="softmax")\n])`,
    experiment: { dropout: 0.5, epochs: 30, complexity: 6 },
  },
  {
    slug: "early-stopping",
    code: "M-06",
    title: "EarlyStopping Beacon",
    planet: "uranus",
    planetKo: "천왕성",
    sector: "Generalization",
    orbit: 7,
    level: "심화",
    difficulty: 3,
    time: "10분",
    threat: "Late Epoch Decay",
    reward: "Best Weight Capsule",
    desc: "가장 좋은 순간에 학습을 멈춥니다.",
    summary: "EarlyStopping은 검증 성능이 더 이상 좋아지지 않을 때 학습을 멈춰 과적합을 막습니다.",
    analogy: "운동도 적당히 해야 성장하지, 지나치게 무리하면 오히려 부상당하는 것과 같습니다.",
    concepts: ["Epoch", "Validation Loss", "Patience", "restore_best_weights"],
    steps: ["Epoch가 늘수록 항상 좋아지는 것은 아님을 봅니다.", "검증 손실이 증가하는 시점을 찾습니다.", "patience의 의미를 이해합니다.", "restore_best_weights의 필요성을 정리합니다."],
    codeSnippet: `from tensorflow.keras.callbacks import EarlyStopping\n\nearly_stop = EarlyStopping(\n    monitor="val_loss", patience=5, restore_best_weights=True\n)`,
    experiment: { dropout: 0.2, epochs: 60, complexity: 5 },
  },
  {
    slug: "transfer-learning",
    code: "M-07",
    title: "Transfer Pluto Gate",
    planet: "pluto",
    planetKo: "명왕성",
    sector: "Frontier AI",
    orbit: 9,
    level: "최전선",
    difficulty: 4,
    time: "16분",
    threat: "Small Dataset Barrier",
    reward: "Pretrained Knowledge Key",
    desc: "이미 학습된 모델의 지식을 가져옵니다.",
    summary: "Transfer Learning은 대규모 데이터로 미리 학습된 모델을 가져와 새로운 문제에 활용하는 방법입니다.",
    analogy: "이미 운전을 잘하는 사람이 새 차에 적응하는 것이 처음부터 배우는 것보다 빠른 것과 같습니다.",
    concepts: ["Pretrained Model", "Feature Extractor", "Fine-tuning", "ImageNet"],
    steps: ["Pretrained Model의 의미를 이해합니다.", "Feature Extractor와 Classifier를 구분합니다.", "작은 데이터에서 강한 이유를 봅니다.", "Fine-tuning의 개념을 정리합니다."],
    codeSnippet: `base_model = tf.keras.applications.MobileNetV2(\n    include_top=False, weights="imagenet", input_shape=(224, 224, 3)\n)\nbase_model.trainable = False`,
    experiment: { dropout: 0.3, epochs: 25, complexity: 7 },
  },
  {
    slug: "yolo",
    code: "M-08",
    title: "YOLO Pluto Scanner",
    planet: "pluto",
    planetKo: "명왕성",
    sector: "Frontier AI",
    orbit: 9,
    level: "최전선",
    difficulty: 5,
    time: "22분",
    threat: "Object Detection Fog",
    reward: "Bounding Box Lens",
    desc: "이미지 속 객체를 한 번에 탐지합니다.",
    summary: "YOLO는 이미지를 한 번만 보고 객체의 위치와 종류를 동시에 예측하는 객체 탐지 모델입니다.",
    analogy: "사진을 보고 사람, 자동차, 신호등 위치를 즉시 박스로 표시하는 스캐너와 같습니다.",
    concepts: ["Object Detection", "Bounding Box", "Confidence", "Grid Cell", "NMS"],
    steps: ["분류와 객체 탐지의 차이를 이해합니다.", "Bounding Box의 의미를 확인합니다.", "Confidence Score를 이해합니다.", "YOLO가 빠른 이유를 정리합니다."],
    codeSnippet: `from ultralytics import YOLO\n\nmodel = YOLO("yolov8n.pt")\nresults = model("image.jpg")`,
    experiment: { dropout: 0.1, epochs: 40, complexity: 8 },
  },
  {
    slug: "pca",
    code: "M-09",
    title: "PCA Mars Field",
    planet: "mars",
    planetKo: "화성",
    sector: "Classic ML",
    orbit: 4,
    level: "중급",
    difficulty: 3,
    time: "12분",
    threat: "Dimension Storm",
    reward: "Dimensional Lens",
    desc: "고차원 데이터를 낮은 차원으로 압축합니다.",
    summary: "PCA는 데이터의 중요한 방향을 찾아 고차원 데이터를 낮은 차원으로 압축하는 방법입니다.",
    analogy: "복잡한 3D 물체를 정보가 잘 보이는 각도에서 2D 그림자로 보는 것과 같습니다.",
    concepts: ["Dimensionality Reduction", "Variance", "Principal Component", "Visualization"],
    steps: ["차원이 많을 때 이해가 어려운 이유를 봅니다.", "분산이 큰 방향을 찾습니다.", "2차원으로 줄여 시각화합니다.", "정보 손실과 압축의 균형을 정리합니다."],
    codeSnippet: `from sklearn.decomposition import PCA\n\npca = PCA(n_components=2)\nX_2d = pca.fit_transform(X_scaled)`,
    experiment: { dropout: 0, epochs: 15, complexity: 4 },
  },
  {
    slug: "kmeans",
    code: "M-10",
    title: "K-Means Mars Arena",
    planet: "mars",
    planetKo: "화성",
    sector: "Classic ML",
    orbit: 4,
    level: "중급",
    difficulty: 3,
    time: "10분",
    threat: "Unknown Label Zone",
    reward: "Cluster Compass",
    desc: "비슷한 데이터끼리 자동으로 묶습니다.",
    summary: "K-Means는 정답 라벨 없이 데이터를 K개의 그룹으로 나누는 비지도학습 알고리즘입니다.",
    analogy: "이름표 없이 모인 사람들을 특징이 비슷한 사람끼리 그룹 짓는 것과 같습니다.",
    concepts: ["Unsupervised Learning", "Cluster", "Centroid", "K Value"],
    steps: ["비지도학습의 의미를 이해합니다.", "중심점이 이동하는 과정을 봅니다.", "K값 선택이 중요한 이유를 확인합니다.", "군집 결과 해석법을 정리합니다."],
    codeSnippet: `from sklearn.cluster import KMeans\n\nmodel = KMeans(n_clusters=3, random_state=42)\nlabels = model.fit_predict(X)`,
    experiment: { dropout: 0, epochs: 12, complexity: 3 },
  },
  {
    slug: "transformer",
    code: "M-11",
    title: "Transformer Neptune Nexus",
    planet: "neptune",
    planetKo: "해왕성",
    sector: "Transformer",
    orbit: 8,
    level: "고급",
    difficulty: 5,
    time: "25분",
    threat: "Context Collapse",
    reward: "Attention Matrix",
    desc: "문맥을 연결하는 Self-Attention 구조입니다.",
    summary: "Transformer는 Self-Attention을 이용해 문장 속 단어들이 서로 어떤 관계인지 학습합니다.",
    analogy: "문장을 읽을 때 각 단어가 주변 단어와 어떤 관련이 있는지 동시에 바라보는 방식입니다.",
    concepts: ["Self-Attention", "Query", "Key", "Value", "Embedding", "LLM"],
    steps: ["RNN과 Transformer의 차이를 이해합니다.", "Self-Attention의 역할을 봅니다.", "Query, Key, Value를 확인합니다.", "현대 생성형 AI의 기반 구조를 정리합니다."],
    codeSnippet: `# Attention(Q, K, V) = softmax(QK^T / sqrt(d_k)) V\nattention_scores = Q @ K.T\nattention_weights = softmax(attention_scores)\noutput = attention_weights @ V`,
    experiment: { dropout: 0.2, epochs: 50, complexity: 9 },
  },
];

export const stats = {
  totalMissions: missions.length,
  planets: planets.length,
  concepts: missions.reduce((acc, mission) => acc + mission.concepts.length, 0),
};

export function getPlanet(key: PlanetKey) {
  return planets.find((planet) => planet.key === key) ?? planets[0];
}
